## 
## load libraries
library(Matrix)
library(Seurat)
library(openxlsx)
library(ggplot2)
library(ggfortify)
library(jcolors)
require(gridExtra)
library(grid)
library(matrixStats)
library(tidyverse)
library(RColorBrewer)
library(parallel)
library(plotly)
library(sctransform)
library(glassoFast)
library(igraph)
library(ggraph)
library(graphlayouts)
library(Signac)
library(Seurat)
library(patchwork)
library(hdf5r)
library(GenomeInfoDbData)
library(GenomicRanges)
library(GenomicAlignments)
library(Biostrings)
library(rtracklayer)
library(GenomicFeatures)
library(bedtoolsr)
library(tidytext)
library(circlize)
library(doParallel)
library(edgeR)
library(patchwork)
library(doParallel)
library(ggVennDiagram)
library(viridis)
library(MyEllipsefit)
library(princurve)
library(plotly)
library(VennDiagram)







